In [ ]:
import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import numpy as np

In [15]:
l = ([ '1','2','3', '4','5'],)


In [16]:
 np.array(object = l)

array([['1', '2', '3', '4', '5']], dtype='<U1')

In [27]:
ar =  np.array(l)

In [28]:
ar

array([['1', '2', '3', '4', '5']], dtype='<U1')

In [29]:
type(ar)

numpy.ndarray

In [45]:
l =([('sudhir','lodhi','singh',)])

In [46]:
np.asanyarray(l)

array([['sudhir', 'lodhi', 'singh']], dtype='<U6')

In [51]:
l=np.array(l)

In [52]:
l.dtype

dtype('<U6')

In [32]:
l1=[1,2,3,4,5,6]

In [33]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [34]:
s=np.array(l1)

In [36]:
s.dtype

dtype('int64')

In [37]:
np.array([(2.3,3.2,2),(2.1,5.3,8)])

array([[2.3, 3.2, 2. ],
       [2.1, 5.3, 8. ]])

In [38]:
l2 =np.array([(2.3,3.2,2),(2.1,5.3,8)])

In [40]:
l2.dtype

dtype('float64')

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [ ]:
(1) Shape -

In [1]:
import  numpy  as np

In [3]:
np.array(['sudhir','singh]','lodhi','bhsi',])

array(['sudhir', 'singh]', 'lodhi', 'bhsi'], dtype='<U6')

In [9]:
ar = np.array([['sudhir','singh]','lodhi','bhsi',]])

In [10]:
ar

array([['sudhir', 'singh]', 'lodhi', 'bhsi']], dtype='<U6')

In [11]:
ar.shape

(1, 4)

In [ ]:
(2) Size _

In [13]:
ar

array([['sudhir', 'singh]', 'lodhi', 'bhsi']], dtype='<U6')

In [14]:
ar.size

4

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
                  [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [17]:
import numpy as np

In [20]:
np.zeros((3,3,))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
arr = np.zeros((3,3,))

In [22]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr.size

9

In [24]:
arr.shape

(3, 3)

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

                [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
ar2=np.zeros((5,5))

In [35]:
ar2[0,0] = 1

In [36]:
ar2

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
ar2.shape

(5, 5)